
baseURL = "https://example.com/"

[module]
    [module.hugoVersion]
        min = "0.116.0"
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-jslibs-dist/alpinejs/v3"
    [[module.imports]]
        path = "github.com/olivernn/lunr.js"
        [[module.imports.mounts]]
            source = "lunr.js"
            target = "assets/js/lib/lunr.js"
    [[module.imports]]
        path = "github.com/slatedocs/slate"
        [[module.imports.mounts]]
            source = "source/images"
            target = "static/images"
        [[module.imports.mounts]]
            source = "source/fonts"
            target = "static/fonts"
        [[module.imports.mounts]]
            source = "source/stylesheets"
            target = "assets/scss/slate"
